#!bin/bash

if [ "$REPLICATION" ]; then
   if [ "$REPLICATION_NODE" -eq 1 ]; then
cat > /tmp/start_replication.sql <<-EOF
    GRANT REPLICATION SLAVE ON *.* TO '$REPLICATION_SLAVE_USER'@'localhost' IDENTIFIED BY '$REPLICATION_SLAVE_PASSWORD';
EOF
    mysql -u root -p$MYSQL_ROOT_PASSWORD < /tmp/start_replication.sql
   fi
    if [ "$REPLICATION_NODE" -eq 2 ]; then
        #override config slave
        mv /etc/mysql/my_slave.cnf /etc/mysql/my.cnf

cat > /tmp/start_replication.sql <<-EOF
STOP SLAVE;
CHANGE MASTER TO MASTER_HOST='mysql', MASTER_USER='root', MASTER_PASSWORD='$MYSQL_ROOT_PASSWORD', MASTER_PORT=3306, master_log_file='mysqld-bin.000001',master_log_pos=120;
START SLAVE;
EOF
    mysql -u root -p$MYSQL_ROOT_PASSWORD < /tmp/start_replication.sql
    
    fi
fi



